Us 08 nav bar
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #11
Opened 2024-09-10 08:46 UTC by Adiallo123

2024-09-10 14:57 UTC, Pyriac requested changes

2024-09-10 14:57 UTC, Pyriac commented on client/src/components/NavBar.jsx
> +      <article className={`Brand_Title `}>
enlever les accolades

2024-09-10 14:57 UTC, Pyriac commented on client/src/components/NavBar.jsx
> +      <article className={`Brand_Title `}>
Sauf erreur de ma part il n'y a pas de classe CSS à ce nom, peut-être juste la remove ?

2024-09-10 14:57 UTC, Pyriac commented on client/src/components/NavBar.jsx
> +      <div className={`Brand_Nav Mobile `}>
Pareil, ça marche sans, remove le class name ?

2024-09-10 15:12 UTC, Pyriac approved these changes
ça me paraît bon

2024-09-10 15:13 UTC, perecornello approved these changes

2024-09-11 06:50 UTC, kpeset approved these changes

2024-09-11 06:50 UTC, merged