Us 14 register company
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #17
Opened 2024-09-12 15:35 UTC by Adiallo123

2024-09-12 21:30 UTC, Pyriac requested changes
je pense qu'il y a quelques trucs à revoirs ! On peut regarder ça ensemble si tu veux 😸

2024-09-12 21:30 UTC, Pyriac commented on client/src/pages/RegisterCompay.jsx
> +          if(password === confirmPassword){
tu fais cette vérification dans le front et dans le back, les deux sont-elles nécéssaires ?

2024-09-12 21:30 UTC, Pyriac commented on server/app/services/auth.js
> +const verifPassword = async(req, res, next) => {
L'autre vérification est là, enlever celle du front ?

2024-09-12 21:30 UTC, Pyriac commented on client/src/pages/RegisterCompay.jsx
> +            const response = await fetch(
ici on a une méthode d'export dans un formulaire classique mais tu utilises le Form de react-router-dom ligne 87

2024-09-12 21:30 UTC, Pyriac commented on client/src/main.jsx
> +        element: <RegisterCompany />,
si tu veux utiliser le Form avec la méthode post il faudra un action ici, sinon tu peux remove ton form dans RegisterCompay :)

2024-09-12 21:30 UTC, Pyriac commented on client/src/pages/RegisterCompay.jsx
> +import { useState } from "react";
il manque un N dans le nom du fichier, à voir si on le refait 😅

2024-09-12 21:30 UTC, Pyriac commented on server/app/services/auth.js
> +    const regex = /[A-Z]/;
Bravo le regex 😄

2024-09-12 21:30 UTC, Pyriac commented on server/app/services/auth.js
> +        if(password === confirmPassword){
testé dans le front aussi, à voir lequel des deux tu préfères 😎

2024-09-17 07:40 UTC, Pyriac approved these changes
tout semble ok, keep going ✨

2024-09-17 07:41 UTC, perecornello approved these changes
Nice Job Aissatou

2024-09-17 07:54 UTC, kpeset requested changes

2024-09-17 07:54 UTC, kpeset commented on server/app/services/auth.js
> +function contientCaractere(password) {
Jamais de nom de fonction en français :)

2024-09-17 07:54 UTC, kpeset commented on server/app/services/auth.js
> +        if(password === confirmPassword){
Joi serait bien plus adapté que de  faire le regex et la vérification à la main, car il y a beaucoup trop de conditions.

2024-09-17 14:25 UTC, kpeset approved these changes

2024-09-17 14:25 UTC, merged