Us 19 login candidate
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #22
Opened 2024-09-17 15:44 UTC by perecornello

2024-09-17 16:12 UTC, geloanto approved these changes
ggs

2024-09-18 07:22 UTC, Pyriac requested changes

2024-09-18 07:22 UTC, Pyriac commented on server/app/controllers/CandidateActions.js
> +  console.info(candidate);
Petit console.info à remove et c'est parfait 💪

2024-09-18 07:36 UTC, Pyriac approved these changes
Chapeau monsieur ! Maintenant, le front 🐐

2024-09-18 08:38 UTC, kpeset approved these changes

2024-09-18 08:38 UTC, kpeset requested changes
Conflits :)

2024-09-18 08:59 UTC, kpeset approved these changes

2024-09-18 08:59 UTC, merged