login client and create file login-company
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #24
Opened 2024-09-19 14:49 UTC by geloanto

2024-09-19 15:13 UTC, Pyriac requested changes
Des micros ajustements pour ne pas avoir à revenir dessus la semaine prochaine ! Vous êtes des champions 🥇

2024-09-19 15:13 UTC, Pyriac commented on client/src/pages/LoginCompany.jsx
> +            <h2>Inscrivez vous en remplissant le formulaire !</h2>
Ce serait plutôt Connectez-vous non ? Ou alors Link vers le form d'inscription ?

2024-09-19 15:13 UTC, Pyriac commented on server/app/services/companyAuth.js
> +      confirmPassword: Joi.string().min(6).required(),
la méthode pour comparer les mots de passes avec joi : 

confirmPassword: Joi.string()
  .valid(Joi.ref("password"))
  .required()
  .messages({
    "any.only": "Les mots de passe doivent être identiques",
    "string.empty": "Le champ de confirmation du mot de passe est obligatoire"
  }),

Bravo pour le reste c'est giga clean 💪

2024-09-19 15:21 UTC, Pyriac requested changes

2024-09-19 15:21 UTC, Pyriac commented on server/app/services/companyAuth.js
> +      confirmPassword: Joi.string().min(6).required(),
Nevermind, on vérifie ailleurs vous embêtez pas 🌝

2024-09-20 08:25 UTC, Pyriac approved these changes
niquel top bravo !

2024-09-20 12:05 UTC, samihringuet approved these changes

2024-09-20 12:07 UTC, geoffpech approved these changes
GG !! =)

2024-09-20 13:14 UTC, kpeset approved these changes

2024-09-20 13:14 UTC, merged