Us19 02 create login
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #26
Opened 2024-09-19 17:50 UTC by geoffpech

2024-09-20 12:04 UTC, Pyriac approved these changes
Tout me paraît bon !

2024-09-20 12:21 UTC, Adiallo123 approved these changes
top!

2024-09-20 13:24 UTC, kpeset requested changes

2024-09-20 13:24 UTC, kpeset commented on client/src/context/AuthentificationContext.jsx
> +  const logout = () => {
La fonction logout ne fait pas de requête api pour delete le cookie ?

2024-09-20 13:29 UTC, geoffpech commented on client/src/context/AuthentificationContext.jsx
> +  const logout = () => {
pour l'instant nop je vais regarder now pour l'implementer =)

2024-09-22 08:36 UTC, kpeset approved these changes

2024-09-22 08:36 UTC, merged