Us 01 table
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #3
Opened 2024-08-28 13:55 UTC by Adiallo123

2024-08-28 14:29 UTC, geoffpech approved these changes
Jolie travail je valide !!!!! =)

2024-08-28 14:44 UTC, kpeset reviewed
Il faut de la cohérence dans les noms des fichiers :)
Pourquoi avoir nommé AnnoncesRepository alors que tu as nommé un fichier EntrepriseRepository ?
Spoiler alert = on met tout au singulier ;) (donc AnnonceRepository)

2024-08-28 14:47 UTC, kpeset requested changes

2024-08-28 14:47 UTC, kpeset commented on server/database/schema.sql
> +create table annonces (
Les noms de table doivent être au singulier ;)

2024-08-28 14:47 UTC, kpeset commented on server/database/schema.sql
> +  intituler_de_poste VARCHAR(155) not NULL,
pas de français dans les noms de colonnes

2024-08-28 14:47 UTC, kpeset commented on server/database/schema.sql
> +create table entreprise (
Les noms de tables ne doivent pas être en français

2024-08-28 14:47 UTC, kpeset commented on server/database/models/EntrepriseRepository.js
> +class EntrepriseRepository extends AbstractRepository{
Les noms ne doivent pas être en français.
Ici il y a entreprise, alors que ça devrait être enterprise

2024-08-28 15:21 UTC, Pyriac approved these changes
Good job ! Everything was in english now !
See ya tomorrow 💂

2024-08-28 15:21 UTC, Pyriac commented on server/database/tables.js
> +tables.annonces = new AnnounceRepository();
reste un mot en français

2024-08-28 15:23 UTC, geoffpech approved these changes
GOOD JOB !

2024-08-28 15:25 UTC, kpeset requested changes
Il me faudrait maintenant 4 insert into ! :)
Deux pour company et deux pour announce :)
Faire le npm run db migrate, et voir si il y a pas eu de lézard ;)

2024-08-28 15:25 UTC, kpeset commented on server/database/schema.sql
> +  company_name VARCHAR(155) NOT NULL,
juste name ;)
sinon ça fera bizarre quand un moment on voudra faire compagny.company_name ;)
Sinon pour quoi pas mettre company_password, company_phone etc... Tu me suis :) ?

2024-08-28 15:25 UTC, kpeset commented on server/database/schema.sql
> +  company_size INT NOT NULL,
Pareil ;)

2024-08-28 15:49 UTC, perecornello approved these changes
everything is tested and ok

2024-08-28 15:50 UTC, Pyriac approved these changes
well done, got the data !

2024-08-28 15:51 UTC, geoffpech approved these changes
GOOD !

2024-08-29 10:15 UTC, kpeset approved these changes
C'est parfait :)

2024-08-29 10:15 UTC, merged