Announce Detail
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-externatic pull request #8
Opened 2024-09-04 14:23 UTC by perecornello

Created 2 pages ( AnnounceDetail , announceDetailLoader)/modified AnnounceCard and main

2024-09-04 14:28 UTC, geloanto approved these changes
great job

2024-09-04 14:32 UTC, geoffpech approved these changes
C'est GG je penses =) a voir peut etre j'ai raté un truc ^^

2024-09-06 08:21 UTC, kpeset approved these changes
Parfait !

2024-09-06 08:21 UTC, kpeset requested changes
Conflits ^^

2024-09-06 09:02 UTC, kpeset approved these changes
C'est beau !

2024-09-06 09:02 UTC, merged